apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: pmkv-smail
spec:
  build:
    secrets:
      - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "34e53bfb-6ef7-4e2c-8831-00a3a8b1de4e"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET